version: 'version'

services:
  service_maria:
    image: "image_maria"
    ports:
      - "8080:80"
      - 443:443
  service_angelo:
    image: "image_angelo"
    labels:
      - "dchc.enable=true"
      - "dchc.protocol=tcp"
      - "dchc.hostname=archive.ubuntu.com"
      - "dchc.port=22"
      - "dchc.http.endpoint=/"
      - "dchc.http.method=GET"
      - "dchc.timeout=3"
      - "dchc.retries=3"
    ports:
      - 82:80
      - 22:443
  service_joao:
    image: "image_joao"
    labels:
      - "dchc.enable=true"
      - "dchc.protocol=http"
      - "dchc.hostname=archive.ubuntu.com"
      - "dchc.http.endpoint=/"
      - "dchc.http.method=GET"
      - "dchc.timeout=3"
      - "dchc.retries=3"
    ports:
      - 80
      - "23"

volumes:
  volume_maria:
    driver: local
