services:
  maria:
    image: "maria"
    ports:
      - 81:80
      - 443:443
  angelo:
    image: "angelo"
    labels:
      - "dchc.enable=true"
      - "dchc.protocol=tcp"
      - "dchc.hostname=archive.ubuntu.com"
      - "dchc.port=22"
      - "dchc.http.endpoint=/"
      - "dchc.http.method=GET"
      - "dchc.timeout=3"
      - "dchc.retries=3"
    ports:
      - 82:80
      - 443:443
  joao:
    image: "joao"
    labels:
      - "dchc.enable=true"
      - "dchc.protocol=http"
      - "dchc.hostname=archive.ubuntu.com"
      - "dchc.port=80"
      - "dchc.http.endpoint=/"
      - "dchc.http.method=GET"
      - "dchc.timeout=3"
      - "dchc.retries=3"
    ports:
      - 80:80
      - 443:443
